### ISSUE TITLE
Add optional extra labels for all kubernetes objects.

### ISSUE THREAD

**Issue by MarcFriedhoff** [SoftwareAG/webmethods-helm-charts#1]
Add for all generated kubernetes objects optional labels in order to query objects at runtime by custom labels.

  labels:
...
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}

**Comment by thomas-2020** [comment]
Implemented in commit 6cb85a7846587269b0e32a9e57ebb6e032b0ddce
