### ISSUE TITLE
Request for new API Gateway helm chart release

### ISSUE THREAD

**Issue by cospeedster** [SoftwareAG/webmethods-helm-charts#116]
Hello @thomas-2020,

could you please release a new helm chart version which includes #114 ?

Regards

**Comment by thomas-2020** [comment]
I have agreed last week the PR and all jobs for rollout/deployment were running. Maybe to get the last changes, you must refresh your local Helm Chart cache.

**Comment by cospeedster** [comment]
Hello @thomas-2020,

the newest version that i can find is `1.2.9` which we are currently using:

```
vagrant@dev:~$ helm repo ls
NAME            URL                                                             
webmethods      https://open-source.softwareag.com/webmethods-helm-charts/charts

vagrant@dev:~$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "webmethods" chart repository
Update Complete. ⎈Happy Helming!⎈

vagrant@dev:~$ helm search repo apigateway --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                          
webmethods/apigateway   1.2.9           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.8           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.7           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.6           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.5           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.4           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.3           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.2           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.1           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.2.0           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.1.0           10.15           API Gateway Helm Chart for Kubernetes
webmethods/apigateway   1.0.0           10.15           API Gateway Helm Chart for Kubernetes
```

Am I missing something?

**Comment by thomas-2020** [comment]
Your changes are in `1.2.9`. I have not created a new version.

**Comment by cospeedster** [comment]
Hello @thomas-2020,

I'm a bit confused right now. My colleague updated the chart version for our deployment to `1.2.9` back in september.

Are you overwriting chart release versions or what happened? Is there something like a release note for each version?

**Comment by thomas-2020** [comment]
I didn't create a new version (or release notes) because the changes were backward compatible. Do you need a version `1.2.10`?

**Comment by cospeedster** [comment]
Hello @thomas-2020,

no, I don't technically need a new version. However, it feels unsafe not to assign new versions for changes. This could possibly break deployments of your customers.

If we really wanted to be sure that our production workloads were only changed by ourselves, we would then have to keep every version on hand to protect it against upstream changes.

I don't want to be petty, but if you follow conventions like semver, the next chart version would be the 1.3.0 because the change adds a new feature from the helm chart perspektive.

For now, I live with the way it is, but the versioning concept should be explained in the readme.

What are your thoughts on that?

**Comment by thomas-2020** [comment]
You changes are very good and I agree to set the new version to `2.0.0`.
I would like to document the migration in the `apigateway/helm/README.me.gotmpl` file. I would like to do this but I don't how to catch your branch. Do you have an idea?
Another point what I want to do is regarding the value `revisionHistoryLimit`. Currently, it is commended in `values.yaml` and therefore not visible in README.me. Would you uncommented (so it should explicit set) ?

**Comment by cospeedster** [comment]
Hi @thomas-2020,
I tried to add you to my branch. Can you try to propose your changes [here](https://github.com/cospeedster/webmethods-helm-charts/tree/patch-2)?
Yes, I uncommented it ([ecb82d29a1ed77feee032842ab540b2ec10c3e10](https://github.com/SoftwareAG/webmethods-helm-charts/commit/ecb82d29a1ed77feee032842ab540b2ec10c3e10)) I set it to the default value `10` so that it will not break existing deployments of other customers.

**Comment by thomas-2020** [comment]
So, I have cloned your branch and will test the migration in my test environment

**Comment by thomas-2020** [comment]
I have merged your branch. Did you see it? Can we close this issue?

**Comment by cospeedster** [comment]
I have decided to close this issue because helm itself describes that a chart version has to follow [SemVer 2](https://semver.org/spec/v2.0.0.html) in their [documentation](https://helm.sh/docs/topics/charts/#charts-and-versioning).
