### ISSUE TITLE
API Gateway: Set up without Prometheus Operator

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-helm-charts#14]
It should be possible to set up API Gateway without the Prometheus Operator. Some users might not want to use Prometheus at all, or they might want to use an externally managed Prometheus instance, for example Azure Management Prometheus.

**Comment by thesse1** [comment]
I am running the API Gateway chart with default value file. It does not work because the Prometheus Operator is not installed. Therefore, we should either add the Prometheus Operator as a prerequisite in our documentation, or we should change the default value file and disable the use of the Prometheus Operator.

**Comment by MarcFriedhoff** [comment]
As you already provided a pull request, you can close this issue once the pull request is approved and merged.

**Comment by thesse1** [comment]
Pull request is merged.
