### ISSUE TITLE
API Gateway: How to configure Elasticsearch resources?

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-helm-charts#36]
In values.yaml, I see a resources block for API Gateway and for Kibana, but not for Elasticsearch. Also in kibana.yaml, I see spec.podTemplate.spec.containers, but I do not see such a block in elasticsearch.yaml. How can I define resources for Elasticsearch containers?

**Comment by MarcFriedhoff** [comment]
HI Thomas, you can define your own resources / nodeSet  by overriding the nodeSets property with your own configuration: 

  # -- Node sets. See official ElasticSearch documentation at:
  # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html
  # if you specify node sets here the defaultNodeSet will not be used.
  nodeSets: []

**Comment by MarcFriedhoff** [comment]
Fixed with PR #40
