### ISSUE TITLE
Error in file name for the ConfigMap

### ISSUE THREAD

**Issue by enginsarlak** [SoftwareAG/webmethods-helm-charts#46]
https://github.com/SoftwareAG/webmethods-helm-charts/blame/deec72b0b1eace66dfa4a85229932795d6e2680d/universalmessaging/helm/README.md#L22

This command creates the ConfigMap as ```licencekey``` and container is looking for a file ```licence.xml```. This is misleading and very easy to overlook. What is the correct kubectl command supposed to be?
```kubectl create configmap universalmessaging-licence-key --from-file=licence.xml=```

**Comment by MarcFriedhoff** [comment]
@enginsarlak There is indeed an issue with the ConfigMap that can be created if you provide a license as value. We will fix this.

However the command:

`kubectl create configmap universalmessaging-licence-key --from-file=licence.xml=<your licence file>`

creates the correct ConfigMap that is mapped to the file licence.xml in the container which is expected by UM. So I am not sure what issue you are facing.

**Comment by thomas-2020** [comment]
Fixes in UM Helm Chart version `1.0.3` and MSR Readme
