### ISSUE TITLE
Couldn't make this work after copy paste. 

### ISSUE THREAD

**Issue by enginsarlak** [SoftwareAG/webmethods-helm-charts#47]
https://github.com/SoftwareAG/webmethods-helm-charts/blame/deec72b0b1eace66dfa4a85229932795d6e2680d/microservicesruntime/examples/msr-defaults/README.md#L59

It is not clear how and where these defaults supposed to be copied. An example having the actual values.vaml file would be really helpful. I couldn't make this work after copying it in to values.yaml file. The error I get is below. The error message is not clear to me. 

Error: INSTALLATION FAILED: failed to parse <patch to valuesyaml file>/values.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}

**Comment by MarcFriedhoff** [comment]
@enginsarlak I have added the corresponding surrounding element (propertiesFile.content) in the README of the example for the defaults. Hope this is now clearer to you - please also check the MSR READMEand the corresponding value description.
