### ISSUE TITLE
License not in ConfigMap

### ISSUE THREAD

**Issue by thomas-2020** [SoftwareAG/webmethods-helm-charts#59]
I use the license key inside values.yaml ...

```
...
# -- Create a secret manually in cluster which contains all the necessary certs, files etc. for all the servers as well as tmc as the same secret will be mounted to all the pods deployed via this helm chart.
secretName:
# -- The license content for the Terracotta cluster. Required.
license: |
  Date of Issue: 2023-11-22
  Expiration Date: 2026-12-10
...
```
The license.key file in ConfigMap is empty  ...
![image](https://github.com/SoftwareAG/webmethods-helm-charts/assets/56643065/06de62c7-bfc1-446d-8a7c-ccf7200b0366)
---
(I am a little confused because this was already working)

**Comment by mathieucarbou** [comment]
Please note that it works, 100% sure, and we have smoke tests on our helm charts ;-)

Just run as written in the README:

`helm install <release-name> --set-file terracotta.license=<license-file> --set tag=4.3.10-SNAPSHOT `

For example, we start our non-secured smoke tests with:

```
launch helm install "my-release" \
  --set-file terracotta.license=license.key \
  --set terracotta.stripeCount=2 \
  --set terracotta.nodeCountPerStripe=2 \
  --set terracotta.offHeapSize=512m \
  --set terracotta.datastoreSize=512m \
  --set registry=iregistry.eur.ad.sag \
  --set serverImage=terracotta/bigmemorymax-server \
  --set tmcImage=terracotta/bigmemorymax-tmc \
  --set tag=$VERSION \
  $helm_path
```

**Comment by thomas-2020** [comment]
You have changed the layout of `values.yaml`. Now is the value `license` under `terracotta`. With the last `values.yaml` is the deployment successfully.

**Comment by mathieucarbou** [comment]
yes. this setting is bound to terracotta: this is a tc license key.
