### ISSUE TITLE
Integration Server container shuts down if license doens't have MSR 

### ISSUE THREAD

**Issue by enginsarlak** [SoftwareAG/webmethods-helm-charts#66]
IS container expects MSR license to inject application.properties file. 
Steps to reproduce, 
Update the MSR repo url to IS container repo.
Add license file as indicated in helm readme (as config map). 
Helm install using a license without MSR capabilities.  

As recommended, setting/adding the parameter `--set microservicesruntime.licenseKeyProvided=false` made container work but it made it start with a trial license, not the license I have provided. The trial license is set to expire in 90 days so this workaround doesn't work for me. 

Is there a way to keep using values.yaml file and IS containers with these helm charts? 

Related container logs are attached below. 

```
jvm 1    | 2024-02-06 18:31:30 GMT [ISS.0028.9999I] Validating License file for Microservices
jvm 1    | 2024-02-06 18:31:30 GMT [ISS.0028.0103I] License file /opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml is not enabled for the Microservices functionality.
jvm 1    | 2024-02-06 18:31:30 GMT [ISS.0028.9999C] The license provided is invalid or cannot be read. Remove application.properties file or provide a valid MSR license.
jvm 1    | 2024-02-06 18:31:30 GMT [ISS.0028.9999C] com.softwareag.is.dynamicvariables.DynamicVariablesCriticalException: The license provided is invalid or cannot be read. Remove application.properties file or provide a valid MSR license.
jvm 1    | 	at com.softwareag.is.dynamicvariables.DynamicVariablesManager.processDynamicVariables(DynamicVariablesManager.java:351)
jvm 1    | 	at com.wm.app.b2b.server.Server.run(Server.java:469)
jvm 1    | 
jvm 1    | [ProxyLogManager] reset() -> com.webmethods.sc.logging.jul.HandlerLogManager@30e753f6
jvm 1    | [Tue Feb 06 18:31:31 GMT 2024] [INFO] Bootstrap: Stopping...
jvm 1    | [ProxyLogManager] setDelegate: com.webmethods.sc.logging.jul.HandlerLogManager@30e753f6 -> com.softwareag.platform.jul.proxy.DefaultLogManager@22a637e7
jvm 1    | [Tue Feb 06 18:31:32 GMT 2024] [INFO] Bootstrap: Stopped
```

**Comment by thomas-2020** [comment]
I think you should set `microservicesruntime.installDir` to `/opt/softwareag/IntegrationServer/instances/default` in your `values.yaml` in this case.

**Comment by thomas-2020** [comment]
Sorry, it seems to be that MSR needs always a LK.

**Comment by enginsarlak** [comment]
LK? Does it mean I can't use these helm charts with integration server license alone? Is there a workaround I can apply?

**Comment by thomas-2020** [comment]
Has you created your own MSR/IS image. Then you need always a license key (LK). The MSR image in `containers.softwareag.com` has an own Trail license. Only in this case is `--set microservicesruntime.licenseKeyProvided=false` working.
