### ISSUE TITLE
Service monitor breaks deployment and MSR ingress doesn't work properly

### ISSUE THREAD

**Issue by enginsarlak** [SoftwareAG/webmethods-helm-charts#76]
MSR ingress doesn't work properly when using path. same yaml configuration works for umserver. I tried merging with the latest and tried again, now I can't deploy anymore after uninstall.  I compared the generated ingress yamls for both um and msr and haven't seen anything important.  Deployment error is below. 

`Error: INSTALLATION FAILED: template: microservicesruntime/templates/servicemonitor.yaml:20:14: executing "microservicesruntime/templates/servicemonitor.yaml" at <.Values.serviceMonitor.enabled>: nil pointer evaluating interface {}.enabled`

**Comment by thomas-2020** [comment]
Your `values.yaml` is working with (MSR) version `1.0.3`. You should set the Chart version option how mentioned on https://github.com/SoftwareAG/webmethods-helm-charts/tree/main?tab=readme-ov-file#chart-versions.
Or, if you want to go to `1.0.4` latest, you should merge your `values.yaml` with the latest changes (with setting and adding `serviceMonitor.enabled`).

**Comment by enginsarlak** [comment]
It was already merged with the latest. Where do I add that serviceMonitor.enabled ? Anywhere is fine?

**Comment by thomas-2020** [comment]
Q: Where?
A: You can use [latest values.yaml](https://github.com/SoftwareAG/webmethods-helm-charts/blob/20fc1518f7ac358c9caea7fc51cd9395cc7a423f/microservicesruntime/helm/values.yaml#L347) as an example.
Q: Anywhere?
A: Yes
