### ISSUE TITLE
Add optional CRD ServiceMonitor for TMC

### ISSUE THREAD

**Issue by thomas-2020** [SoftwareAG/webmethods-helm-charts#79]
Some Customer's K8S cluster environments require a CRD `ServiceMonitor` to scrap metrics by Prometheus operator. Prometheus annotations will not work. You can use (copy/past) the `ServiceMonitor` from MSR chart.

**Comment by mathieucarbou** [comment]
@mobasherul : can you please check ?

**Comment by mobasherul** [comment]
> @mobasherul : can you please check ?

@mathieucarbou Should i add this service monitor to terracotta helm charts?

**Comment by mathieucarbou** [comment]
> > @mobasherul : can you please check ?
> 
> @mathieucarbou Should i add this service monitor to terracotta helm charts?

I'm on vacation for 1 week... I don't know: maybe discuss with the team ? If we can add it and still be backward compatible then I would say yes.
