### ISSUE TITLE
should be kubectl create secret generic ...

### ISSUE THREAD

**Issue by enginsarlak** [SoftwareAG/webmethods-helm-charts#83]
https://github.com/SoftwareAG/webmethods-helm-charts/blame/20fc1518f7ac358c9caea7fc51cd9395cc7a423f/mywebmethodsserver/helm/values.yaml#L207

```kubectl create secret mws-secret --from-literal=user=mwsuser --from-literal=password=mypassword```
should be 
```kubectl create secret generic mws-secret --from-literal=user=mwsuser --from-literal=password=mypassword```

**Comment by thomas-2020** [comment]
You are right. I will correct it.
